spring:
  application:
    name: medmaster
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    show-sql: true
  datasource:
    url: jdbc:postgresql://localhost:5432/medmaster
    username: postgres
    password: postgres
  flyway:
    enabled: true
    baseline-on-migrate: true
